# Generated by Django 5.0.6 on 2024-06-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informations',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='informations',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='informations',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
