# Generated by Django 5.0.6 on 2024-06-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_informations_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
