# Generated by Django 5.0.6 on 2024-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('class_room', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='collages',
            name='iet_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(),
        ),
    ]
